name: noticias_lat
description: "A premium news application."
publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Paquetes Premium ---
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  visibility_detector: ^0.4.0+2
  video_player: ^2.8.2
  audioplayers: ^6.0.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2
  
  # --- NUEVOS PAQUETES REALES ---
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.6
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21